# Generated by Django 5.1.2 on 2024-10-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_userprofile_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
