# Generated by Django 5.1.2 on 2024-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
