# Generated by Django 5.1.2 on 2024-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_alter_register_user_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='gender',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%M/%D'),
        ),
    ]
